# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from nvidia.omniverse.storage.filefolder.v1alpha import (
    filefolder_service_pb2 as nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in nvidia/omniverse/storage/filefolder/v1alpha/filefolder_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FileFolderServiceStub(object):
    """The FileFolderService is the public API which consuming applications use
    to perform operations on folders.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFolder = channel.unary_unary(
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/CreateFolder",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.CreateFolderRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.CreateFolderResponse.FromString,
            _registered_method=True,
        )
        self.GetFolderMode = channel.unary_unary(
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/GetFolderMode",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.GetFolderModeRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.GetFolderModeResponse.FromString,
            _registered_method=True,
        )
        self.List = channel.unary_stream(
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/List",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListResponse.FromString,
            _registered_method=True,
        )
        self.ListStat = channel.unary_stream(
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/ListStat",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListStatRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListStatResponse.FromString,
            _registered_method=True,
        )
        self.DeleteFolder = channel.unary_unary(
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/DeleteFolder",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.DeleteFolderRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.DeleteFolderResponse.FromString,
            _registered_method=True,
        )


class FileFolderServiceServicer(object):
    """The FileFolderService is the public API which consuming applications use
    to perform operations on folders.
    """

    def CreateFolder(self, request, context):
        """Create a folder at the given resource address"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFolderMode(self, request, context):
        """Determine if this address is within a namespace where folders are a native object, i.e. they can exist on their own.
        This has implications on whether folders disappear on the removal of the last object or not.
        For storages without native folders, some folders might disappear on their own when the last element is removed, i.e. when they were not created by a CreateFolder call.
        For storages with native folders, this will never be the case and all folders have to be removed by calling DeleteFolder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """List the content of the storage at the given resource address
        (-- api-linter: core::0136::verb-noun=disabled
        aip.dev/not-precedent: A better name would be ListFolder --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListStat(self, request, context):
        """List the content of the storage at the given resource address, including resource identities and metadata
        (-- api-linter: core::0136::verb-noun=disabled
        aip.dev/not-precedent: A better name would be ListStatFolder --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteFolder(self, request, context):
        """Delete a folder - this must fail if the folder is not empty"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FileFolderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateFolder": grpc.unary_unary_rpc_method_handler(
            servicer.CreateFolder,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.CreateFolderRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.CreateFolderResponse.SerializeToString,
        ),
        "GetFolderMode": grpc.unary_unary_rpc_method_handler(
            servicer.GetFolderMode,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.GetFolderModeRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.GetFolderModeResponse.SerializeToString,
        ),
        "List": grpc.unary_stream_rpc_method_handler(
            servicer.List,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListResponse.SerializeToString,
        ),
        "ListStat": grpc.unary_stream_rpc_method_handler(
            servicer.ListStat,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListStatRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListStatResponse.SerializeToString,
        ),
        "DeleteFolder": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFolder,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.DeleteFolderRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.DeleteFolderResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService",
        rpc_method_handlers,
    )


# This class is part of an EXPERIMENTAL API.
class FileFolderService(object):
    """The FileFolderService is the public API which consuming applications use
    to perform operations on folders.
    """

    @staticmethod
    def CreateFolder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/CreateFolder",
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.CreateFolderRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.CreateFolderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetFolderMode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/GetFolderMode",
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.GetFolderModeRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.GetFolderModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/List",
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListStat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/ListStat",
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListStatRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.ListStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteFolder(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.filefolder.v1alpha.FileFolderService/DeleteFolder",
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.DeleteFolderRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_filefolder_dot_v1alpha_dot_filefolder__service__pb2.DeleteFolderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
