# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{  $fullName := include "ngsearch.fullname" . -}}

{{- if ne .Values.global.storage_backend_type "multi" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ngsearch.fullname" . }}-backend-config
  labels:
    {{- include "ngsearch.labels" . | nindent 4 }}
data:
  backend.yaml: |
  {{- with .Values.global.search_backend_config }}
    backend_name: {{ .index_name }}
    backend_type: {{ .backend_type }}
    backend_desc: "Search backend"
    host: {{ .host }}
    port: {{ .port }}
    index_name: {{ .index_name }}
  {{- end }}
    word_feats_path: /CLIP/wn_vec_67k.pkl
    ims_per_sample: 8
    hidden_urls:

{{- end }}