# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{  $deploymentSelectorLabels := include "ngsearch.MainDeploymentSelectorlabels" . }}
{{- $values := .Values -}}

{{- if .Values.global.secrets.create.vlm }}
  {{- if .Values.microservices.search_rest_api.validation.enabled }}
{{- $vlm_service := .Values.microservices.search_rest_api.validation.vlm_service -}}

{{- with .Values.microservices.search_rest_api.validation}}  

apiVersion: v1
kind: Secret
type: Opaque
metadata:
{{- if eq $vlm_service "azure_openai"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .azure_openai) | nindent 2}}
{{- else if eq $vlm_service "openai"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .openai) | nindent 2}}
{{- else if eq $vlm_service "anthropic"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .anthropic) | nindent 2}}
{{- else if eq $vlm_service "mistralai"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .mistralai) | nindent 2}}
{{- else if eq $vlm_service "google"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .google) | nindent 2}}
{{- else if eq $vlm_service "nim"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .nim) | nindent 2}}
{{- else if eq $vlm_service "qwen"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .qwen) | nindent 2}}
{{- else if eq $vlm_service "inference_hub"}}
  {{- include "ngsearch.template.vlm.apiKeySecretName" (dict "source" .inference_hub) | nindent 2}}
{{- end }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    {{- toYaml $values.global.secrets.annotations | nindent 4}}
  labels:
    {{- $deploymentSelectorLabels | nindent 4 }}
data:
{{- if eq $vlm_service "azure_openai" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .azure_openai "vlm_type" $vlm_service) | nindent 2}}
{{- else if eq $vlm_service "openai" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .openai "vlm_type" $vlm_service) | nindent 2 }}
{{- else if eq $vlm_service "anthropic" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .anthropic "vlm_type" $vlm_service) | nindent 2 }}
{{- else if eq $vlm_service "mistralai" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .mistralai "vlm_type" $vlm_service) | nindent 2 }}
{{- else if eq $vlm_service "google" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .google "vlm_type" $vlm_service) | nindent 2 }}
{{- else if eq $vlm_service "nim" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .nim "vlm_type" $vlm_service) | nindent 2 }}
{{- else if eq $vlm_service "qwen" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .qwen "vlm_type" $vlm_service) | nindent 2 }}
{{- else if eq $vlm_service "inference_hub" -}}
  {{- include "ngsearch.template.vlm.apiKeySecretValue" (dict "source" .inference_hub "vlm_type" $vlm_service) | nindent 2 }}
{{- end }}
---  
    {{- end }}
  {{- end }}
{{- end }}
