# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/omniverse/storage/capabilities/v1beta/capabilities.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "nvidia/omniverse/storage/capabilities/v1beta/capabilities.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n?nvidia/omniverse/storage/capabilities/v1beta/capabilities.proto\x12,nvidia.omniverse.storage.capabilities.v1beta"\x15\n\x13ListServicesRequest"d\n\x14ListServicesResponse\x12L\n\x08services\x18\x01 \x03(\x0b\x32:.nvidia.omniverse.storage.capabilities.v1beta.ServiceEntry">\n\x0cServiceEntry\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x18\n\x10service_versions\x18\x02 \x03(\t"\x1e\n\x1cListTopLevelAddressesRequest"r\n\x1dListTopLevelAddressesResponse\x12Q\n\x05items\x18\x01 \x03(\x0b\x32\x42.nvidia.omniverse.storage.capabilities.v1beta.TopLevelAddressEntry"1\n\x14TopLevelAddressEntry\x12\x19\n\x11top_level_address\x18\x01 \x01(\t2\xe0\x02\n\x13\x43\x61pabilitiesService\x12\x95\x01\n\x0cListServices\x12\x41.nvidia.omniverse.storage.capabilities.v1beta.ListServicesRequest\x1a\x42.nvidia.omniverse.storage.capabilities.v1beta.ListServicesResponse\x12\xb0\x01\n\x15ListTopLevelAddresses\x12J.nvidia.omniverse.storage.capabilities.v1beta.ListTopLevelAddressesRequest\x1aK.nvidia.omniverse.storage.capabilities.v1beta.ListTopLevelAddressesResponseB\x88\x01\n0com.nvidia.omniverse.storage.capabilities.v1betaB\x11\x43\x61pabilitiesProtoP\x01Z?pb.api.nvidia.com/omniverse/storage/capabilities/v1beta;storageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "nvidia.omniverse.storage.capabilities.v1beta.capabilities_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n0com.nvidia.omniverse.storage.capabilities.v1betaB\021CapabilitiesProtoP\001Z?pb.api.nvidia.com/omniverse/storage/capabilities/v1beta;storage"
    )
    _globals["_LISTSERVICESREQUEST"]._serialized_start = 113
    _globals["_LISTSERVICESREQUEST"]._serialized_end = 134
    _globals["_LISTSERVICESRESPONSE"]._serialized_start = 136
    _globals["_LISTSERVICESRESPONSE"]._serialized_end = 236
    _globals["_SERVICEENTRY"]._serialized_start = 238
    _globals["_SERVICEENTRY"]._serialized_end = 300
    _globals["_LISTTOPLEVELADDRESSESREQUEST"]._serialized_start = 302
    _globals["_LISTTOPLEVELADDRESSESREQUEST"]._serialized_end = 332
    _globals["_LISTTOPLEVELADDRESSESRESPONSE"]._serialized_start = 334
    _globals["_LISTTOPLEVELADDRESSESRESPONSE"]._serialized_end = 448
    _globals["_TOPLEVELADDRESSENTRY"]._serialized_start = 450
    _globals["_TOPLEVELADDRESSENTRY"]._serialized_end = 499
    _globals["_CAPABILITIESSERVICE"]._serialized_start = 502
    _globals["_CAPABILITIESSERVICE"]._serialized_end = 854
# @@protoc_insertion_point(module_scope)
