# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from nvidia.omniverse.storage.capabilities.v1beta import (
    capabilities_pb2 as nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in nvidia/omniverse/storage/capabilities/v1beta/capabilities_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CapabilitiesServiceStub(object):
    """The CapabilitiesService is used to reflect on which services are implemented by this server.
    Each service in turn exposes another service-specific capabilities query,
    to read data from remote storage.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListServices = channel.unary_unary(
            "/nvidia.omniverse.storage.capabilities.v1beta.CapabilitiesService/ListServices",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListServicesRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListServicesResponse.FromString,
            _registered_method=True,
        )
        self.ListTopLevelAddresses = channel.unary_unary(
            "/nvidia.omniverse.storage.capabilities.v1beta.CapabilitiesService/ListTopLevelAddresses",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListTopLevelAddressesRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListTopLevelAddressesResponse.FromString,
            _registered_method=True,
        )


class CapabilitiesServiceServicer(object):
    """The CapabilitiesService is used to reflect on which services are implemented by this server.
    Each service in turn exposes another service-specific capabilities query,
    to read data from remote storage.
    """

    def ListServices(self, request, context):
        """Return the list of service API implemented by this service"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTopLevelAddresses(self, request, context):
        """Return a list of top level resource addresses that is suited for browsing this storage service by the user."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CapabilitiesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListServices": grpc.unary_unary_rpc_method_handler(
            servicer.ListServices,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListServicesRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListServicesResponse.SerializeToString,
        ),
        "ListTopLevelAddresses": grpc.unary_unary_rpc_method_handler(
            servicer.ListTopLevelAddresses,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListTopLevelAddressesRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListTopLevelAddressesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nvidia.omniverse.storage.capabilities.v1beta.CapabilitiesService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nvidia.omniverse.storage.capabilities.v1beta.CapabilitiesService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CapabilitiesService(object):
    """The CapabilitiesService is used to reflect on which services are implemented by this server.
    Each service in turn exposes another service-specific capabilities query,
    to read data from remote storage.
    """

    @staticmethod
    def ListServices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.capabilities.v1beta.CapabilitiesService/ListServices",
            nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListServicesRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTopLevelAddresses(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.capabilities.v1beta.CapabilitiesService/ListTopLevelAddresses",
            nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListTopLevelAddressesRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_capabilities_dot_v1beta_dot_capabilities__pb2.ListTopLevelAddressesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
