# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 1
disable_existing_loggers: False
filters:
  otel_disabled_exclude:
    (): deepsearch_api.utils.OTELDisabledWarningFilter
  healthcheck_exclude:
    (): deepsearch_api.utils.AccessLogFilter
  grpc_error_exclude:
    (): deepsearch_api.utils.GRPCCommonFilter
  correlation_id:
    (): asgi_correlation_id.CorrelationIdFilter
    uuid_length: 32
    default_value: '-'
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(levelprefix)s %(asctime)s [%(correlation_id)s] %(name)s - %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(levelprefix)s %(asctime)s [%(correlation_id)s] %(name)s - %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
    filters:
    - correlation_id
    - grpc_error_exclude
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
    filters:
      - correlation_id
      - healthcheck_exclude
loggers:
  root:
    level: INFO
    handlers:
      - default
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
  search_backend_observability:
    level: INFO
    handlers:
      - default
    propagate: no
  websockets.client:
    level: INFO
  deepsearch_api.request_duration_logger:
    level: INFO
    filters:
      - healthcheck_exclude
    handlers:
      - default
    propagate: no
  opentelemetry.sdk.trace:
    filters:
      - otel_disabled_exclude
