# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from nvidia.omniverse.notifications.consumer.v1beta import (
    event_consumer_pb2 as nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in nvidia/omniverse/notifications/consumer/v1beta/event_consumer_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EventConsumerServiceStub(object):
    """EventConsumerService provides APIs for consuming events from the notification system.
    This service provides APIs for consuming events
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsumeDurableEvents = channel.unary_stream(
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/ConsumeDurableEvents",
            request_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeDurableEventsRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeDurableEventsResponse.FromString,
            _registered_method=True,
        )
        self.ConsumeNonDurableEvents = channel.stream_stream(
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/ConsumeNonDurableEvents",
            request_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeNonDurableEventsRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeNonDurableEventsResponse.FromString,
            _registered_method=True,
        )
        self.CreateDurableQueue = channel.unary_unary(
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/CreateDurableQueue",
            request_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.CreateDurableQueueRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.CreateDurableQueueResponse.FromString,
            _registered_method=True,
        )
        self.DeleteDurableQueue = channel.unary_unary(
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/DeleteDurableQueue",
            request_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.DeleteDurableQueueRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.DeleteDurableQueueResponse.FromString,
            _registered_method=True,
        )
        self.UpdateDurableQueue = channel.unary_unary(
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/UpdateDurableQueue",
            request_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.UpdateDurableQueueRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.UpdateDurableQueueResponse.FromString,
            _registered_method=True,
        )


class EventConsumerServiceServicer(object):
    """EventConsumerService provides APIs for consuming events from the notification system.
    This service provides APIs for consuming events
    """

    def ConsumeDurableEvents(self, request, context):
        """ConsumeDurableEvents starts a streaming session to receive events
        using a durable queue.

        This means any events that occurred since the queue was created
        with a call to the CreateDurableQueue RPC will be received,
        even if the events occur while the client is disconnected.

        A RESOURCE_EXHAUSTED status code may be returned if a given k8s pod has an exhausted channel
        pool, and the client should automatically try to reconnect until they
        get a pod with available channels.

        At any time while streaming events, a PERMISSION_DENIED or UNAUTHENTICATED
        status code could be returned,
        for example, if a token becomes expired while streaming.
        The client must handle these errors and reconnect with a valid token.

        Clients should implement automatic reconnection on UNAVAILABLE errors because
        cloud load balancers (AWS NLB/ALB, Azure Load Balancer) may terminate idle
        connections based on their idle timeout settings (typically 60 seconds to 4 minutes).
        These load balancers operate at Layer 4 (TCP) and do not recognize HTTP/2 PING
        frames (gRPC keep-alive) as activity, so they may close idle streams even when
        gRPC keep-alive is configured. The exact timeout depends on the deployment
        environment and infrastructure configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConsumeNonDurableEvents(self, request_iterator, context):
        """ConsumeNonDurableEvents starts a streaming session to receive events
        using a non-durable queue. This means that only events that occur while
        connected will be consumed.

        This is stream-stream, so that additional
        ConsumeNonDurableEventsRequest objects may be sent to change
        filtering while consuming events of a given set of types.

        A RESOURCE_EXHAUSTED status code may be returned if a given k8s pod has an exhausted channel
        pool, and the client should automatically try to reconnect until they
        get a pod with available channels.

        At any time while streaming events, a PERMISSION_DENIED or UNAUTHENTICATED
        status code could be returned,
        for example, if a token becomes expired while streaming.
        The client must handle these errors and reconnect using the reconnect_token
        returned by the initial ConsumeNonDurableEventsResponse to ensure messages
        are not lost.

        Clients should implement automatic reconnection on UNAVAILABLE errors because
        cloud load balancers (AWS NLB/ALB, Azure Load Balancer) may terminate idle
        connections based on their idle timeout settings (typically 60 seconds to 4 minutes).
        These load balancers operate at Layer 4 (TCP) and do not recognize HTTP/2 PING
        frames (gRPC keep-alive) as activity, so they may close idle streams even when
        gRPC keep-alive is configured. The exact timeout depends on the deployment
        environment and infrastructure configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateDurableQueue(self, request, context):
        """CreateDurableQueue is used to create a durable queue which will immediately begin
        receiving and queuing up messages for later consumption.
        The durable queue will exist until it is explicitly deleted
        with a call to DeleteDurableQueue.

        When building a service that uses the Notification APIs,
        this will typically be called outside of the code base
        of that service, and then the "queue_id" value
        retrieved will be used as configuration for that service.

        This is not required for non-durable events.
        E.g., when ConsumeNonDurableEvents is called, the client will only
        receive events that occur while the client is connected.

        A config object will be returned that includes an ID that
        must be reused as an argument in all future ConsumeDurableEvents calls.

        A RESOURCE_EXHAUSTED status code may be returned if a given k8s pod has an exhausted channel
        pool, and the client should automatically try to reconnect until they
        get a pod with available channels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDurableQueue(self, request, context):
        """DeleteDurableQueue is called if a durable consumer queue was created and used, and it is no
        longer required, a delete queue call must be made to free up resources.
        This typically only happens if the consumer client is being taken
        down permanently.

        A RESOURCE_EXHAUSTED status code may be returned if a given k8s pod has an exhausted channel
        pool, and the client should automatically try to reconnect until they
        get a pod with available channels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateDurableQueue(self, request, context):
        """UpdateDurableQueue is used to update the filtering on an existing durable queue that was
        created using CreateDurableQueue.

        The filters will be updated without losing messages.
        This may be preferable to deleting and re-creating the
        durable queue, which may result in lost messages.

        A RESOURCE_EXHAUSTED status code may be returned if a given k8s pod has an exhausted channel
        pool, and the client should automatically try to reconnect until they
        get a pod with available channels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EventConsumerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ConsumeDurableEvents": grpc.unary_stream_rpc_method_handler(
            servicer.ConsumeDurableEvents,
            request_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeDurableEventsRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeDurableEventsResponse.SerializeToString,
        ),
        "ConsumeNonDurableEvents": grpc.stream_stream_rpc_method_handler(
            servicer.ConsumeNonDurableEvents,
            request_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeNonDurableEventsRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeNonDurableEventsResponse.SerializeToString,
        ),
        "CreateDurableQueue": grpc.unary_unary_rpc_method_handler(
            servicer.CreateDurableQueue,
            request_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.CreateDurableQueueRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.CreateDurableQueueResponse.SerializeToString,
        ),
        "DeleteDurableQueue": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDurableQueue,
            request_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.DeleteDurableQueueRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.DeleteDurableQueueResponse.SerializeToString,
        ),
        "UpdateDurableQueue": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateDurableQueue,
            request_deserializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.UpdateDurableQueueRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.UpdateDurableQueueResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class EventConsumerService(object):
    """EventConsumerService provides APIs for consuming events from the notification system.
    This service provides APIs for consuming events
    """

    @staticmethod
    def ConsumeDurableEvents(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/ConsumeDurableEvents",
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeDurableEventsRequest.SerializeToString,
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeDurableEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ConsumeNonDurableEvents(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/ConsumeNonDurableEvents",
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeNonDurableEventsRequest.SerializeToString,
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.ConsumeNonDurableEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateDurableQueue(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/CreateDurableQueue",
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.CreateDurableQueueRequest.SerializeToString,
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.CreateDurableQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteDurableQueue(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/DeleteDurableQueue",
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.DeleteDurableQueueRequest.SerializeToString,
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.DeleteDurableQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateDurableQueue(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.notifications.consumer.v1beta.EventConsumerService/UpdateDurableQueue",
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.UpdateDurableQueueRequest.SerializeToString,
            nvidia_dot_omniverse_dot_notifications_dot_consumer_dot_v1beta_dot_event__consumer__pb2.UpdateDurableQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
