# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/omniverse/storage/capabilities/v1alpha/capabilities.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "nvidia/omniverse/storage/capabilities/v1alpha/capabilities.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n@nvidia/omniverse/storage/capabilities/v1alpha/capabilities.proto\x12-nvidia.omniverse.storage.capabilities.v1alpha"\x15\n\x13ListServicesRequest"e\n\x14ListServicesResponse\x12M\n\x08services\x18\x01 \x03(\x0b\x32;.nvidia.omniverse.storage.capabilities.v1alpha.ServiceEntry">\n\x0cServiceEntry\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x18\n\x10service_versions\x18\x02 \x03(\t"\x1e\n\x1cListTopLevelAddressesRequest"s\n\x1dListTopLevelAddressesResponse\x12R\n\x05items\x18\x01 \x03(\x0b\x32\x43.nvidia.omniverse.storage.capabilities.v1alpha.TopLevelAddressEntry"\x13\n\x11ListRoutesRequest"Y\n\x12ListRoutesResponse\x12\x43\n\x05items\x18\x01 \x03(\x0b\x32\x34.nvidia.omniverse.storage.capabilities.v1alpha.Route"1\n\x14TopLevelAddressEntry\x12\x19\n\x11top_level_address\x18\x01 \x01(\t"1\n\x05Route\x12\x1a\n\x10wildcard_pattern\x18\x01 \x01(\tH\x00\x42\x0c\n\nroute_type2\xf8\x03\n\x13\x43\x61pabilitiesService\x12\x97\x01\n\x0cListServices\x12\x42.nvidia.omniverse.storage.capabilities.v1alpha.ListServicesRequest\x1a\x43.nvidia.omniverse.storage.capabilities.v1alpha.ListServicesResponse\x12\xb2\x01\n\x15ListTopLevelAddresses\x12K.nvidia.omniverse.storage.capabilities.v1alpha.ListTopLevelAddressesRequest\x1aL.nvidia.omniverse.storage.capabilities.v1alpha.ListTopLevelAddressesResponse\x12\x91\x01\n\nListRoutes\x12@.nvidia.omniverse.storage.capabilities.v1alpha.ListRoutesRequest\x1a\x41.nvidia.omniverse.storage.capabilities.v1alpha.ListRoutesResponseB\x8a\x01\n1com.nvidia.omniverse.storage.capabilities.v1alphaB\x11\x43\x61pabilitiesProtoP\x01Z@pb.api.nvidia.com/omniverse/storage/capabilities/v1alpha;storageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "nvidia.omniverse.storage.capabilities.v1alpha.capabilities_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n1com.nvidia.omniverse.storage.capabilities.v1alphaB\021CapabilitiesProtoP\001Z@pb.api.nvidia.com/omniverse/storage/capabilities/v1alpha;storage"
    )
    _globals["_LISTSERVICESREQUEST"]._serialized_start = 115
    _globals["_LISTSERVICESREQUEST"]._serialized_end = 136
    _globals["_LISTSERVICESRESPONSE"]._serialized_start = 138
    _globals["_LISTSERVICESRESPONSE"]._serialized_end = 239
    _globals["_SERVICEENTRY"]._serialized_start = 241
    _globals["_SERVICEENTRY"]._serialized_end = 303
    _globals["_LISTTOPLEVELADDRESSESREQUEST"]._serialized_start = 305
    _globals["_LISTTOPLEVELADDRESSESREQUEST"]._serialized_end = 335
    _globals["_LISTTOPLEVELADDRESSESRESPONSE"]._serialized_start = 337
    _globals["_LISTTOPLEVELADDRESSESRESPONSE"]._serialized_end = 452
    _globals["_LISTROUTESREQUEST"]._serialized_start = 454
    _globals["_LISTROUTESREQUEST"]._serialized_end = 473
    _globals["_LISTROUTESRESPONSE"]._serialized_start = 475
    _globals["_LISTROUTESRESPONSE"]._serialized_end = 564
    _globals["_TOPLEVELADDRESSENTRY"]._serialized_start = 566
    _globals["_TOPLEVELADDRESSENTRY"]._serialized_end = 615
    _globals["_ROUTE"]._serialized_start = 617
    _globals["_ROUTE"]._serialized_end = 666
    _globals["_CAPABILITIESSERVICE"]._serialized_start = 669
    _globals["_CAPABILITIESSERVICE"]._serialized_end = 1173
# @@protoc_insertion_point(module_scope)
