# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/omniverse/storage/metadata/v1alpha/metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "nvidia/omniverse/storage/metadata/v1alpha/metadata.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n8nvidia/omniverse/storage/metadata/v1alpha/metadata.proto\x12)nvidia.omniverse.storage.metadata.v1alpha\x1a\x1cgoogle/protobuf/struct.proto"=\n\x12GetMetadataRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x1a\n\x12user_metadata_keys\x18\x02 \x03(\t"\xf1\x01\n\x13GetMetadataResponse\x12g\n\ruser_metadata\x18\x01 \x03(\x0b\x32P.nvidia.omniverse.storage.metadata.v1alpha.GetMetadataResponse.UserMetadataEntry\x1aq\n\x11UserMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12K\n\x05value\x18\x02 \x01(\x0b\x32<.nvidia.omniverse.storage.metadata.v1alpha.UserMetadataValue:\x02\x38\x01"\x9c\x01\n\x15UpdateMetadataRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x19\n\x11user_metadata_key\x18\x02 \x01(\t\x12-\n\ruser_metadata\x18\x03 \x01(\x0b\x32\x16.google.protobuf.Value\x12\x1a\n\rexpected_etag\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_expected_etag"&\n\x16UpdateMetadataResponse\x12\x0c\n\x04\x65tag\x18\x01 \x01(\t"m\n\x15\x44\x65leteMetadataRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x19\n\x11user_metadata_key\x18\x02 \x01(\t\x12\x1a\n\rexpected_etag\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_expected_etag"\x18\n\x16\x44\x65leteMetadataResponse"H\n\x11UserMetadataValue\x12%\n\x05value\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Value\x12\x0c\n\x04\x65tag\x18\x02 \x01(\t2\xd0\x03\n\x0fMetadataService\x12\x8c\x01\n\x0bGetMetadata\x12=.nvidia.omniverse.storage.metadata.v1alpha.GetMetadataRequest\x1a>.nvidia.omniverse.storage.metadata.v1alpha.GetMetadataResponse\x12\x95\x01\n\x0eUpdateMetadata\x12@.nvidia.omniverse.storage.metadata.v1alpha.UpdateMetadataRequest\x1a\x41.nvidia.omniverse.storage.metadata.v1alpha.UpdateMetadataResponse\x12\x95\x01\n\x0e\x44\x65leteMetadata\x12@.nvidia.omniverse.storage.metadata.v1alpha.DeleteMetadataRequest\x1a\x41.nvidia.omniverse.storage.metadata.v1alpha.DeleteMetadataResponseB~\n-com.nvidia.omniverse.storage.metadata.v1alphaB\rMetadataProtoP\x01Z<pb.api.nvidia.com/omniverse/storage/metadata/v1alpha;storageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "nvidia.omniverse.storage.metadata.v1alpha.metadata_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n-com.nvidia.omniverse.storage.metadata.v1alphaB\rMetadataProtoP\001Z<pb.api.nvidia.com/omniverse/storage/metadata/v1alpha;storage"
    )
    _globals["_GETMETADATARESPONSE_USERMETADATAENTRY"]._loaded_options = None
    _globals["_GETMETADATARESPONSE_USERMETADATAENTRY"]._serialized_options = b"8\001"
    _globals["_GETMETADATAREQUEST"]._serialized_start = 133
    _globals["_GETMETADATAREQUEST"]._serialized_end = 194
    _globals["_GETMETADATARESPONSE"]._serialized_start = 197
    _globals["_GETMETADATARESPONSE"]._serialized_end = 438
    _globals["_GETMETADATARESPONSE_USERMETADATAENTRY"]._serialized_start = 325
    _globals["_GETMETADATARESPONSE_USERMETADATAENTRY"]._serialized_end = 438
    _globals["_UPDATEMETADATAREQUEST"]._serialized_start = 441
    _globals["_UPDATEMETADATAREQUEST"]._serialized_end = 597
    _globals["_UPDATEMETADATARESPONSE"]._serialized_start = 599
    _globals["_UPDATEMETADATARESPONSE"]._serialized_end = 637
    _globals["_DELETEMETADATAREQUEST"]._serialized_start = 639
    _globals["_DELETEMETADATAREQUEST"]._serialized_end = 748
    _globals["_DELETEMETADATARESPONSE"]._serialized_start = 750
    _globals["_DELETEMETADATARESPONSE"]._serialized_end = 774
    _globals["_USERMETADATAVALUE"]._serialized_start = 776
    _globals["_USERMETADATAVALUE"]._serialized_end = 848
    _globals["_METADATASERVICE"]._serialized_start = 851
    _globals["_METADATASERVICE"]._serialized_end = 1315
# @@protoc_insertion_point(module_scope)
