# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from nvidia.omniverse.storage.metadata.v1alpha import (
    metadata_pb2 as nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in nvidia/omniverse/storage/metadata/v1alpha/metadata_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MetadataServiceStub(object):
    """The MetadataService provides methods to set and retrieve metadata for data objects."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetadata = channel.unary_unary(
            "/nvidia.omniverse.storage.metadata.v1alpha.MetadataService/GetMetadata",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.GetMetadataRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.GetMetadataResponse.FromString,
            _registered_method=True,
        )
        self.UpdateMetadata = channel.unary_unary(
            "/nvidia.omniverse.storage.metadata.v1alpha.MetadataService/UpdateMetadata",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.UpdateMetadataRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.UpdateMetadataResponse.FromString,
            _registered_method=True,
        )
        self.DeleteMetadata = channel.unary_unary(
            "/nvidia.omniverse.storage.metadata.v1alpha.MetadataService/DeleteMetadata",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.DeleteMetadataRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.DeleteMetadataResponse.FromString,
            _registered_method=True,
        )


class MetadataServiceServicer(object):
    """The MetadataService provides methods to set and retrieve metadata for data objects."""

    def GetMetadata(self, request, context):
        """Get metadata for a specific URI"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateMetadata(self, request, context):
        """Update metadata for a specific URI"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteMetadata(self, request, context):
        """Delete metadata for a specific URI"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetMetadata": grpc.unary_unary_rpc_method_handler(
            servicer.GetMetadata,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.GetMetadataRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.GetMetadataResponse.SerializeToString,
        ),
        "UpdateMetadata": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateMetadata,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.UpdateMetadataRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.UpdateMetadataResponse.SerializeToString,
        ),
        "DeleteMetadata": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteMetadata,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.DeleteMetadataRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.DeleteMetadataResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nvidia.omniverse.storage.metadata.v1alpha.MetadataService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nvidia.omniverse.storage.metadata.v1alpha.MetadataService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """The MetadataService provides methods to set and retrieve metadata for data objects."""

    @staticmethod
    def GetMetadata(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.metadata.v1alpha.MetadataService/GetMetadata",
            nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.GetMetadataRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateMetadata(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.metadata.v1alpha.MetadataService/UpdateMetadata",
            nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.UpdateMetadataRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.UpdateMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteMetadata(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nvidia.omniverse.storage.metadata.v1alpha.MetadataService/DeleteMetadata",
            nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.DeleteMetadataRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_metadata_dot_v1alpha_dot_metadata__pb2.DeleteMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
