# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/omniverse/storage/fileobject/v1beta/fileobject.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "nvidia/omniverse/storage/fileobject/v1beta/fileobject.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n;nvidia/omniverse/storage/fileobject/v1beta/fileobject.proto\x12*nvidia.omniverse.storage.fileobject.v1beta\x1a\x1fgoogle/protobuf/timestamp.proto"\x16\n\x05\x43hunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c"\x9c\x01\n\x08Metadata\x12\x1d\n\x10\x64\x61ta_object_size\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12@\n\x17last_modified_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x42\x13\n\x11_data_object_sizeB\x1a\n\x18_last_modified_timestamp"%\n\x06Header\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"\x8b\x01\n\x08Redirect\x12\x1b\n\x13redirect_target_url\x18\x01 \x01(\t\x12\x12\n\x06method\x18\x02 \x01(\tB\x02\x18\x01\x12N\n\x12\x61\x64\x64itional_headers\x18\x03 \x03(\x0b\x32\x32.nvidia.omniverse.storage.fileobject.v1beta.Header"o\n\x0b\x41\x64\x64ressInfo\x12\x18\n\x10resource_address\x18\x01 \x01(\t\x12\x46\n\x08metadata\x18\x02 \x01(\x0b\x32\x34.nvidia.omniverse.storage.fileobject.v1beta.Metadata"\xaf\x01\n\x0cResourceInfo\x12W\n\x11resource_identity\x18\x01 \x01(\x0b\x32<.nvidia.omniverse.storage.fileobject.v1beta.ResourceIdentity\x12\x46\n\x08metadata\x18\x02 \x01(\x0b\x32\x34.nvidia.omniverse.storage.fileobject.v1beta.Metadata",\n\x10ResourceIdentity\x12\x18\n\x10\x65ncoded_identity\x18\x01 \x01(\tB\x82\x01\n.com.nvidia.omniverse.storage.fileobject.v1betaB\x0f\x46ileobjectProtoP\x01Z=pb.api.nvidia.com/omniverse/storage/fileobject/v1beta;storageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "nvidia.omniverse.storage.fileobject.v1beta.fileobject_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n.com.nvidia.omniverse.storage.fileobject.v1betaB\017FileobjectProtoP\001Z=pb.api.nvidia.com/omniverse/storage/fileobject/v1beta;storage"
    )
    _globals["_REDIRECT"].fields_by_name["method"]._loaded_options = None
    _globals["_REDIRECT"].fields_by_name["method"]._serialized_options = b"\030\001"
    _globals["_CHUNK"]._serialized_start = 140
    _globals["_CHUNK"]._serialized_end = 162
    _globals["_METADATA"]._serialized_start = 165
    _globals["_METADATA"]._serialized_end = 321
    _globals["_HEADER"]._serialized_start = 323
    _globals["_HEADER"]._serialized_end = 360
    _globals["_REDIRECT"]._serialized_start = 363
    _globals["_REDIRECT"]._serialized_end = 502
    _globals["_ADDRESSINFO"]._serialized_start = 504
    _globals["_ADDRESSINFO"]._serialized_end = 615
    _globals["_RESOURCEINFO"]._serialized_start = 618
    _globals["_RESOURCEINFO"]._serialized_end = 793
    _globals["_RESOURCEIDENTITY"]._serialized_start = 795
    _globals["_RESOURCEIDENTITY"]._serialized_end = 839
# @@protoc_insertion_point(module_scope)
