# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from nvidia.omniverse.storage.versioning.v1alpha import (
    versioning_pb2 as nvidia_dot_omniverse_dot_storage_dot_versioning_dot_v1alpha_dot_versioning__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in nvidia/omniverse/storage/versioning/v1alpha/versioning_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class VersioningServiceStub(object):
    """The VersioningService provides methods to manage versions of data objects."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnumerateVersions = channel.unary_stream(
            "/nvidia.omniverse.storage.versioning.v1alpha.VersioningService/EnumerateVersions",
            request_serializer=nvidia_dot_omniverse_dot_storage_dot_versioning_dot_v1alpha_dot_versioning__pb2.EnumerateVersionsRequest.SerializeToString,
            response_deserializer=nvidia_dot_omniverse_dot_storage_dot_versioning_dot_v1alpha_dot_versioning__pb2.EnumerateVersionsResponse.FromString,
            _registered_method=True,
        )


class VersioningServiceServicer(object):
    """The VersioningService provides methods to manage versions of data objects."""

    def EnumerateVersions(self, request, context):
        """List versions of a data object at the specified resource address."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VersioningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "EnumerateVersions": grpc.unary_stream_rpc_method_handler(
            servicer.EnumerateVersions,
            request_deserializer=nvidia_dot_omniverse_dot_storage_dot_versioning_dot_v1alpha_dot_versioning__pb2.EnumerateVersionsRequest.FromString,
            response_serializer=nvidia_dot_omniverse_dot_storage_dot_versioning_dot_v1alpha_dot_versioning__pb2.EnumerateVersionsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nvidia.omniverse.storage.versioning.v1alpha.VersioningService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "nvidia.omniverse.storage.versioning.v1alpha.VersioningService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class VersioningService(object):
    """The VersioningService provides methods to manage versions of data objects."""

    @staticmethod
    def EnumerateVersions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/nvidia.omniverse.storage.versioning.v1alpha.VersioningService/EnumerateVersions",
            nvidia_dot_omniverse_dot_storage_dot_versioning_dot_v1alpha_dot_versioning__pb2.EnumerateVersionsRequest.SerializeToString,
            nvidia_dot_omniverse_dot_storage_dot_versioning_dot_v1alpha_dot_versioning__pb2.EnumerateVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
