# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/omniverse/storage/versioning/v1beta/versioning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "nvidia/omniverse/storage/versioning/v1beta/versioning.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nvidia.omniverse.storage.fileobject.v1beta import (
    fileobject_pb2 as nvidia_dot_omniverse_dot_storage_dot_fileobject_dot_v1beta_dot_fileobject__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n;nvidia/omniverse/storage/versioning/v1beta/versioning.proto\x12*nvidia.omniverse.storage.versioning.v1beta\x1a;nvidia/omniverse/storage/fileobject/v1beta/fileobject.proto"4\n\x18\x45numerateVersionsRequest\x12\x18\n\x10resource_address\x18\x01 \x01(\t"\xb6\x01\n\x19\x45numerateVersionsResponse\x12\x46\n\x05items\x18\x01 \x03(\x0b\x32\x37.nvidia.omniverse.storage.versioning.v1beta.VersionInfo\x12Q\n\x0eversions_order\x18\x02 \x01(\x0e\x32\x39.nvidia.omniverse.storage.versioning.v1beta.VersionsOrder"\x88\x01\n\x0bVersionInfo\x12O\n\rresource_info\x18\x01 \x01(\x0b\x32\x38.nvidia.omniverse.storage.fileobject.v1beta.ResourceInfo\x12\x18\n\x0bsorting_key\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_sorting_key*\x8c\x01\n\rVersionsOrder\x12\x1e\n\x1aVERSIONS_ORDER_UNSPECIFIED\x10\x00\x12\x1f\n\x1bVERSIONS_ORDER_NEWEST_FIRST\x10\x01\x12\x1f\n\x1bVERSIONS_ORDER_OLDEST_FIRST\x10\x02\x12\x19\n\x15VERSIONS_ORDER_BY_KEY\x10\x03\x32\xb8\x01\n\x11VersioningService\x12\xa2\x01\n\x11\x45numerateVersions\x12\x44.nvidia.omniverse.storage.versioning.v1beta.EnumerateVersionsRequest\x1a\x45.nvidia.omniverse.storage.versioning.v1beta.EnumerateVersionsResponse0\x01\x42\x82\x01\n.com.nvidia.omniverse.storage.versioning.v1betaB\x0fVersioningProtoP\x01Z=pb.api.nvidia.com/omniverse/storage/versioning/v1beta;storageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "nvidia.omniverse.storage.versioning.v1beta.versioning_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n.com.nvidia.omniverse.storage.versioning.v1betaB\017VersioningProtoP\001Z=pb.api.nvidia.com/omniverse/storage/versioning/v1beta;storage"
    )
    _globals["_VERSIONSORDER"]._serialized_start = 547
    _globals["_VERSIONSORDER"]._serialized_end = 687
    _globals["_ENUMERATEVERSIONSREQUEST"]._serialized_start = 168
    _globals["_ENUMERATEVERSIONSREQUEST"]._serialized_end = 220
    _globals["_ENUMERATEVERSIONSRESPONSE"]._serialized_start = 223
    _globals["_ENUMERATEVERSIONSRESPONSE"]._serialized_end = 405
    _globals["_VERSIONINFO"]._serialized_start = 408
    _globals["_VERSIONINFO"]._serialized_end = 544
    _globals["_VERSIONINGSERVICE"]._serialized_start = 690
    _globals["_VERSIONINGSERVICE"]._serialized_end = 874
# @@protoc_insertion_point(module_scope)
