# coding: utf-8
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Asset Graph Service API

 The **Asset Graph Service (AGS) API** provides advanced querying capabilities for assets and USD trees indexed in a graph database. It supports proximity queries based on coordinates or prims to find objects within specified areas or radii, sorted by distance, and includes transformation options for vector alignment. The API also offers dependency and reverse dependency searches, helping to identify all assets referenced in a scene or scenes containing a particular asset, which can optimize scene loading and track dependency changes. By combining different query types, the AGS API enables complex scenarios for scene understanding, manipulation, and generation. It can also be integrated with DeepSearch to provide in-scene search functionality.  ## Features  - **Proximity Queries:**   - Find objects within a specified bounding box or radius.   - Results sorted by distance with options for vector alignment using a transformation matrix.  - **USD Property Queries:**      - Enables querying objects in a 3D scene using USD properties, such as finding all assets with a specific semantic label.       - **Asset Dependency Searches:**   - Identify all assets referenced in a scene - including USD references, material references, or textures.   - Reverse search to find all scenes containing a particular asset.  - **Combined Query Capabilities:**   - Enable complex scenarios for enhanced scene understanding, manipulation, and generation.  - **Integration with DeepSearch:**   - Provides in-scene search functionality.

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class AXIS(str, Enum):
    """
    AXIS
    """

    """
    allowed enum values
    """
    X = "X"
    Y = "Y"
    Z = "Z"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AXIS from a JSON string"""
        return cls(json.loads(json_str))
