# coding: utf-8
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Asset Graph Service API

 The **Asset Graph Service (AGS) API** provides advanced querying capabilities for assets and USD trees indexed in a graph database. It supports proximity queries based on coordinates or prims to find objects within specified areas or radii, sorted by distance, and includes transformation options for vector alignment. The API also offers dependency and reverse dependency searches, helping to identify all assets referenced in a scene or scenes containing a particular asset, which can optimize scene loading and track dependency changes. By combining different query types, the AGS API enables complex scenarios for scene understanding, manipulation, and generation. It can also be integrated with DeepSearch to provide in-scene search functionality.  ## Features  - **Proximity Queries:**   - Find objects within a specified bounding box or radius.   - Results sorted by distance with options for vector alignment using a transformation matrix.  - **USD Property Queries:**      - Enables querying objects in a 3D scene using USD properties, such as finding all assets with a specific semantic label.       - **Asset Dependency Searches:**   - Identify all assets referenced in a scene - including USD references, material references, or textures.   - Reverse search to find all scenes containing a particular asset.  - **Combined Query Capabilities:**   - Enable complex scenarios for enhanced scene understanding, manipulation, and generation.  - **Integration with DeepSearch:**   - Provides in-scene search functionality.

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from asset_graph_service_client.models.axis import AXIS
from asset_graph_service_client.models.prim import Prim
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class SceneSummaryResponse(BaseModel):
    """
    SceneSummaryResponse
    """  # noqa: E501

    scene_url: StrictStr
    scene_mpu: Optional[Union[StrictFloat, StrictInt]]
    scene_up_axis: Optional[AXIS]
    n_prims: StrictInt = Field(description="Number of prims in the scene.")
    prim_types: Dict[str, StrictInt] = Field(description="Number of prims per type.")
    unique_property_keys: Dict[str, StrictInt] = Field(description="Number of unique property keys.")
    unique_properties: Dict[str, StrictInt] = Field(description="Number of unique property (key,value) pairs.")
    referenced_assets: Dict[str, StrictInt] = Field(description="Number of unique assets referenced by the scene.")
    default_prim: Optional[Prim] = None
    __properties: ClassVar[List[str]] = [
        "scene_url",
        "scene_mpu",
        "scene_up_axis",
        "n_prims",
        "prim_types",
        "unique_property_keys",
        "unique_properties",
        "referenced_assets",
        "default_prim",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SceneSummaryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_prim
        if self.default_prim:
            _dict["default_prim"] = self.default_prim.to_dict()
        # set to None if scene_mpu (nullable) is None
        # and model_fields_set contains the field
        if self.scene_mpu is None and "scene_mpu" in self.model_fields_set:
            _dict["scene_mpu"] = None

        # set to None if scene_up_axis (nullable) is None
        # and model_fields_set contains the field
        if self.scene_up_axis is None and "scene_up_axis" in self.model_fields_set:
            _dict["scene_up_axis"] = None

        # set to None if default_prim (nullable) is None
        # and model_fields_set contains the field
        if self.default_prim is None and "default_prim" in self.model_fields_set:
            _dict["default_prim"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SceneSummaryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "scene_url": obj.get("scene_url"),
                "scene_mpu": obj.get("scene_mpu"),
                "scene_up_axis": obj.get("scene_up_axis"),
                "n_prims": obj.get("n_prims"),
                "prim_types": obj.get("prim_types"),
                "unique_property_keys": obj.get("unique_property_keys"),
                "unique_properties": obj.get("unique_properties"),
                "referenced_assets": obj.get("referenced_assets"),
                "default_prim": (Prim.from_dict(obj["default_prim"]) if obj.get("default_prim") is not None else None),
            }
        )
        return _obj
