{
 "title": "USD Search / Plugin Processing Dashboard (latest)",
 "tags": [
  "usdsearch",
  "omniverse",
  "nvidia"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(omni_service_process_cpu_percent{component=\"deepsearch\"},namespace)"
    }
   },
   {
    "name": "omni_instance",
    "label": "instance",
    "query": {
     "query": "label_values(omni_service_process_cpu_percent{namespace=\"$namespace\"},release_name)"
    }
   },
   {
    "name": "service_version",
    "label": "deployment version",
    "query": {
     "query": "label_values(omni_service_process_cpu_percent{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"deepsearch\"},version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (omni_service) (time() - process_start_time_seconds{release_name=\"$omni_instance\", component=\"deepsearch\", namespace=\"$namespace\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Indexing performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total processed assets (per plugin) /s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (plugin_name) (rate(omnideepsearch_plugin_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{plugin_name}}"
    },
    {
     "expr": "sum(rate(omnideepsearch_plugin_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Total processed assets/s [5min avg]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) (rate(omnideepsearch_plugin_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{plugin_name}}"
    },
    {
     "expr": "sum(rate(omnideepsearch_plugin_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Total processed assets (per plugin)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) (omnideepsearch_plugin_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{plugin_name}}"
    }
   ]
  },
  {
   "title": "Unique processed assets (per plugin) /s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (plugin_name) (rate(omnideepsearch_plugin_unique_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{plugin_name}}"
    },
    {
     "expr": "sum(rate(omnideepsearch_plugin_unique_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Unique processed assets/s [5min avg]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) (rate(omnideepsearch_plugin_unique_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{plugin_name}}"
    },
    {
     "expr": "sum(rate(omnideepsearch_plugin_unique_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Unique processed assets (per plugin)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) (omnideepsearch_plugin_unique_items_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{plugin_name}}"
    }
   ]
  },
  {
   "title": "Crawler processed items /s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(omnideepsearch_deepsearch_crawler_group_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Crawler processed items/s [5min avg]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(omnideepsearch_deepsearch_crawler_group_processed{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Crawler processed items",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(omnideepsearch_deepsearch_crawler_group_processed{namespace=\"$namespace\"})",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Results queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(omnideepsearch_results_queue_size{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "result"
    }
   ]
  },
  {
   "title": "Results queue size change [items/s]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(deriv(omnideepsearch_results_queue_size{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "result"
    }
   ]
  },
  {
   "title": "Results queue size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(omnideepsearch_results_queue_size{release_name=\"$omni_instance\", namespace=\"$namespace\"}))",
     "legendFormat": "result"
    }
   ]
  },
  {
   "title": "Results queue processing ETA",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((1-omnideepsearch_results_queue_size{release_name=\"$omni_instance\", namespace=\"$namespace\"}/(deriv(omnideepsearch_results_queue_size{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))) > 0 OR vector(-1))",
     "legendFormat": "result"
    }
   ]
  },
  {
   "title": "Plugin tasks queue (priority)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (plugin_name) (omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"priority-group\"})",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Queue size change [items/s] (priority)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "sum by (plugin_name) (deriv(omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"priority-group\"}[$__rate_interval]))",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Queue size (priority)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (plugin_name) (omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"priority-group\"})",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Queue processing ETA (priority)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) ((1-omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"priority-group\"}/(deriv(omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"priority-group\"}[$__rate_interval]))) > 0)",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Plugin tasks queue (background)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (plugin_name) (omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"deepsearch-worker-pool\"})",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Queue size change [items/s] (background)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum by (plugin_name) (deriv(omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"deepsearch-worker-pool\"}[$__rate_interval]))",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Queue size (background)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (plugin_name) (omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"deepsearch-worker-pool\"})",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Queue processing ETA (background)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) ((1-omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"deepsearch-worker-pool\"}/(deriv(omnideepsearch_worker_plugin_tasks_count_per_group{release_name=\"$omni_instance\", namespace=\"$namespace\", group_name=\"deepsearch-worker-pool\"}[$__rate_interval]))) > 0)",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Worker statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Items processed/s ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(omnideepsearch_worker_processed_items_total{release_name=\"$omni_instance\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{worker_type}} {{instance}}"
    },
    {
     "expr": "sum(rate(omnideepsearch_worker_processed_items_total{worker_type=\"farm\", release_name=\"$omni_instance\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Sum [Farm]"
    },
    {
     "expr": "sum(rate(omnideepsearch_worker_processed_items_total{worker_type=\"non_farm\", release_name=\"$omni_instance\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Sum [Non-farm]"
    }
   ]
  },
  {
   "title": "Items processed/s (5min avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (worker_type) (rate(omnideepsearch_worker_processed_items_total{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{ worker_type }}"
    }
   ]
  },
  {
   "title": "Items processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (worker_type) (omnideepsearch_worker_processed_items_total{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ worker_type }}"
    }
   ]
  },
  {
   "title": "Omni writer statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Items processed/s ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(omnideepsearch_writer_processed_items_total{release_name=\"$omni_instance\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "sum(rate(omnideepsearch_writer_processed_items_total{release_name=\"$omni_instance\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Items processed/s (5min avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(omnideepsearch_writer_processed_items_total{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Items processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(omnideepsearch_writer_processed_items_total{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Item processing time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(omnideepsearch_writer_item_processing_duration_seconds_bucket{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch processing time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(omnideepsearch_writer_batch_processing_duration_seconds_bucket{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Item processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(omnideepsearch_writer_item_processing_duration_seconds_sum{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]) / rate(omnideepsearch_writer_item_processing_duration_seconds_count{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Batch processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(omnideepsearch_writer_batch_processing_duration_seconds_sum{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval])/rate(omnideepsearch_writer_batch_processing_duration_seconds_count{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Crawler statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Crawler indexing status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "omnideepsearch_deepsearch_monitor_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}",
     "legendFormat": "processed items"
    },
    {
     "expr": "omnideepsearch_deepsearch_monitor_queued{omni_instance=\"$omni_instance\"}",
     "legendFormat": "queued items"
    }
   ]
  },
  {
   "title": "Farm statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total number of initiated rendering jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum by (plugin_name) (omnideepsearch_running_farm_rendering_jobs{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ plugin_name }}"
    },
    {
     "expr": "omnideepsearch_running_farm_rendering_unique_items{omni_instance=\"$omni_instance\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Unique items being rendered"
    }
   ]
  },
  {
   "title": "Pending items (per plugin)",
   "type": "stat",
   "description": "Items could be pending due to the limited number of GPU resources available for rendering.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) (omnideepsearch_rendering_stream_length{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "Active rendering jobs (per plugin)",
   "type": "stat",
   "description": "Rendering job for these assets have already been created on the cluster.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_name) (omnideepsearch_running_farm_rendering_jobs{release_name=\"$omni_instance\", namespace=\"$namespace\"} - omnideepsearch_rendering_stream_length{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ plugin_name }}"
    }
   ]
  },
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(omni_service_process_cpu_percent{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"deepsearch\"}, \"plugin_instance\", \"$1\", \"pod\", \".*deepsearch-(.*)\")",
     "legendFormat": "{{ plugin_instance }}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", type=\"rss\", component=\"deepsearch\"}, \"plugin_instance\", \"$1\", \"pod\", \".*deepsearch-(.*)\") / 1024 / 1024",
     "legendFormat": "{{ plugin_instance }}"
    }
   ]
  },
  {
   "title": "VMS",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 10, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", type=\"vms\", component=\"deepsearch\"} / 1024 / 1024, \"plugin_instance\", \"$1\", \"pod\", \".*deepsearch-(.*)\")",
     "legendFormat": "{{ plugin_instance }}"
    }
   ]
  },
  {
   "title": "Thread number",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(omni_service_process_num_threads{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"deepsearch\"}, \"plugin_instance\", \"$1\", \"pod\", \".*deepsearch-(.*)\")",
     "legendFormat": "{{ plugin_instance }}"
    }
   ]
  }
 ]
}