{
 "title": "USD Search / Metadata Indexing and Crawler Dashboard (latest)",
 "tags": [
  "usdsearch",
  "omniverse",
  "nvidia"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(omni_service_process_cpu_percent,namespace)"
    }
   },
   {
    "name": "omni_instance",
    "label": "instance",
    "query": {
     "query": "label_values(omni_service_process_cpu_percent{omni_service=\"deepsearch-nucleus-indexing\", namespace=\"$namespace\"},release_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(omni_service_process_cpu_percent{release_name=\"$omni_instance\", component=\"ngsearch\"},version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (omni_service) (time()-process_start_time_seconds{namespace=\"$namespace\", component=\"ngsearch\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Crawler stream length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(omnideepsearch_deepsearch_crawler_stream_length{namespace=\"$namespace\", release_name=\"$omni_instance\"})",
     "legendFormat": "Indexing"
    }
   ]
  },
  {
   "title": "Processing rate (30 sec avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(stream_group) (rate(omnideepsearch_deepsearch_crawler_group_processed{namespace=\"$namespace\", release_name=\"$omni_instance\"}[$__rate_interval]))",
     "legendFormat": "{{stream_group}}"
    }
   ]
  },
  {
   "title": "Processed items [per group]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(stream_group) (omnideepsearch_deepsearch_crawler_group_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ stream_group }}"
    }
   ]
  },
  {
   "title": "Items read/s (5min avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(omnideepsearch_deepsearch_crawler_group_read{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])) by (stream_group)",
     "legendFormat": "{{stream_group}}"
    }
   ]
  },
  {
   "title": "Items read/s (5min avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(omnideepsearch_deepsearch_crawler_group_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])) by (stream_group)",
     "legendFormat": "{{stream_group}}"
    }
   ]
  },
  {
   "title": "Listing change [items/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "deriv(omnideepsearch_deepsearch_crawler_list_subscription{release_name=\"$omni_instance\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "list subscription ({{service}})"
    },
    {
     "expr": "deriv(omnideepsearch_deepsearch_crawler_mount_listing{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "mount re-listing ({{service}})"
    },
    {
     "expr": "deriv(omnideepsearch_deepsearch_crawler_tag_subscription{release_name=\"$omni_instance\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "tag subscription ({{service}})"
    }
   ]
  },
  {
   "title": "Items read/s (5min avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(omnideepsearch_deepsearch_crawler_list_subscription{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "list subscription"
    },
    {
     "expr": "rate(omnideepsearch_deepsearch_crawler_mount_listing{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "mount re-listing"
    },
    {
     "expr": "rate(omnideepsearch_deepsearch_crawler_tag_subscription{release_name=\"$omni_instance\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "tag subscription"
    }
   ]
  },
  { "title": "Indexing Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Indexing service processing status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(omningsearch_indexing_cached{release_name=\"$omni_instance\", namespace=\"$namespace\"} / (omningsearch_indexing_cached{release_name=\"$omni_instance\", namespace=\"$namespace\"} + omningsearch_indexing_queued{release_name=\"$omni_instance\", namespace=\"$namespace\"} + omningsearch_indexing_backlog{release_name=\"$omni_instance\", namespace=\"$namespace\"}) * 100)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Processing rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(omningsearch_indexing_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of Indexing workers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(omningsearch_indexing_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Indexing service queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(omningsearch_indexing_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Indexing"
    }
   ]
  },
  {
   "title": "Indexing service cached items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(omningsearch_indexing_cached{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "Indexing"
    }
   ]
  },
  {
   "title": "Tag crawler processing status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1e-6 + omningsearch_tag_crawler_cached{release_name=\"$omni_instance\", namespace=\"$namespace\"}) / (omningsearch_tag_crawler_cached{release_name=\"$omni_instance\", namespace=\"$namespace\"} + omningsearch_tag_crawler_queued{release_name=\"$omni_instance\", namespace=\"$namespace\"} + omningsearch_tag_crawler_backlog{release_name=\"$omni_instance\", namespace=\"$namespace\"} + 1e-6) * 100)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Processing rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(omningsearch_tag_crawler_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number Tag Crawler workers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(omningsearch_tag_crawler_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Tag crawler queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(omningsearch_tag_crawler_processed{release_name=\"$omni_instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Tag Crawler"
    }
   ]
  },
  {
   "title": "Tag crawler cached items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(omningsearch_tag_crawler_cached{release_name=\"$omni_instance\", namespace=\"$namespace\"})",
     "legendFormat": "Tag Crawler"
    }
   ]
  },
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "omni_service_process_cpu_percent{release_name=\"$omni_instance\", namespace=\"$namespace\", stream_consumer_name !=\"\", component=\"ngsearch\"}",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_cpu_percent{release_name=\"$omni_instance\", namespace=\"$namespace\", stream_consumer_name=\"\", component=\"ngsearch\" }",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_cpu_percent{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"deepsearch-crawler\"}",
     "legendFormat": "{{container}}-{{instance}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", stream_consumer_name!=\"\", type=\"rss\", component=\"ngsearch\"} / 1024 / 1024",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", stream_consumer_name=\"\", type=\"rss\", component=\"ngsearch\"} / 1024 / 1024",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"deepsearch-crawler\", type=\"rss\"} / 1024 / 1024",
     "legendFormat": "{{container}}-{{instance}}"
    }
   ]
  },
  {
   "title": "VMS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", stream_consumer_name!=\"\",  type=\"vms\", component=\"ngsearch\"} / 1024 / 1024",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", stream_consumer_name=\"\",  type=\"vms\", component=\"ngsearch\"} / 1024 / 1024",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_memory_info{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"deepsearch-crawler\",  type=\"vms\"} / 1024 / 1024",
     "legendFormat": "{{container}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Thread number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "omni_service_process_num_threads{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"ngsearch\", stream_consumer_name!=\"\"}",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_num_threads{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"ngsearch\", stream_consumer_name=\"\"}",
     "legendFormat": "{{container}}-{{instance}}"
    },
    {
     "expr": "omni_service_process_num_threads{release_name=\"$omni_instance\", namespace=\"$namespace\", component=\"deepsearch-crawler\"}",
     "legendFormat": "{{container}}-{{instance}}"
    }
   ]
  }
 ]
}