{
 "title": "USD Search / Rendering Service Monitoring (latest)",
 "tags": [
  "usdsearch",
  "omniverse",
  "nvidia"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(usdsearch_rendering_http_requests_total,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(usdsearch_rendering_http_requests_total{namespace=\"$namespace\"},release_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rendering Jobs statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rendered items / second (history)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "5 m average"
    },
    {
     "expr": "sum(rate(usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"}[15m]))",
     "legendFormat": "15 min average"
    },
    {
     "expr": "sum(rate(usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"}[1h]))",
     "legendFormat": "1 hour average"
    }
   ]
  },
  {
   "title": "rendered items / second (average over 5 mins)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rendered items / second (history)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(status) (rate(usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"}[5m])) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "rendered items / second / status (average over 5 mins)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rendering jobs total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count(usdsearch_rendering_http_requests_total{component=\"rendering-service\", release_name=\"$instance\", namespace=\"$namespace\", handler=\"/health\"})",
     "legendFormat": "rendering jobs"
    }
   ]
  },
  {
   "title": "rendering jobs total",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(usdsearch_rendering_http_requests_total{component=\"rendering-service\", release_name=\"$instance\", namespace=\"$namespace\", handler=\"/health\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Kit processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total Kit processes (historical)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "count(usdsearch_rendering_kit_process_memory_percentage{release_name=\"$instance\", namespace=\"$namespace\"} > 0)",
     "legendFormat": "active kit instances"
    }
   ]
  },
  {
   "title": "Total Kit processes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(usdsearch_rendering_kit_process_memory_percentage{release_name=\"$instance\", namespace=\"$namespace\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kit processes RAM utilization buckets",
   "type": "heatmap",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "usdsearch_rendering_kit_process_memory_percentage{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}-{{worker_id}}"
    }
   ]
  },
  {
   "title": "Kit processes (memory)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "usdsearch_rendering_kit_process_memory_percentage{release_name=\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}-{{worker_id}}"
    }
   ]
  },
  {
   "title": "Kit processes (rendering timeout)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "usdsearch_rendering_kit_process_rendering_time_percentage{release_name=\"$instance\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}-{{worker_id}}"
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(usdsearch_rendering_http_requests_total{namespace=\"$namespace\", status=\"2xx\", handler=\"/usdsearch/render\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(usdsearch_rendering_http_requests_total{namespace=\"$namespace\", status=\"5xx\", handler=\"/usdsearch/render\"})",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Success (%)",
   "type": "gauge",
   "description": "successful renders (empty scenes scenes response)",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(usdsearch_rendering_http_requests_total{namespace=\"$namespace\", status=\"2xx\", handler=\"/usdsearch/render\"}) / sum(usdsearch_rendering_http_requests_total{namespace=\"$namespace\", status=~\"5xx|2xx\", handler=\"/usdsearch/render\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures (%)",
   "type": "gauge",
   "description": "Failures due to timeout, OOM or others",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(usdsearch_rendering_http_requests_total{namespace=\"$namespace\", status=\"5xx\", handler=\"/usdsearch/render\"}) / sum(usdsearch_rendering_http_requests_total{namespace=\"$namespace\", status=~\"2xx|5xx\", handler=\"/usdsearch/render\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by(status) (usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rendering status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (usdsearch_rendering_response_status{status!=\"process_limit_reached\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}