# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{  $global := .Values.global -}}
{{- $values := .Values -}}

{{- if $global.secrets.create.auth }}

  {{- if eq $global.storage_backend_type "s3" }}

{{- if $global.s3proxy.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.s3proxy.jclouds.secret_name | default "s3proxy-credentials" }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  {{ .Values.s3proxy.jclouds.identity_key | default "jclouds-identity" }}: {{ required "Please input S3Proxy Identity: --set global.s3proxy.jclouds.identity=<S3Proxy Identity>" .Values.s3proxy.jclouds.identity | toString | b64enc }}
  {{ .Values.s3proxy.jclouds.credential_key | default "jclouds-credential" }}: {{ required "Please input S3Proxy Credential: --set global.s3proxy.jclouds.credential=<S3Proxy Credential>" .Values.s3proxy.jclouds.credential | toString | b64enc }}

{{- else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $global.s3.aws_credentials_secret_name }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ required "Please input AWS access key ID: --set global.s3.aws_access_key_id=<AWS_ACCESS_KEY_ID>" $global.s3.aws_access_key_id | toString | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "Please input AWS secret access key: --set global.s3.aws_secret_access_key=<AWS_SECRET_ACCESS_KEY>" $global.s3.aws_secret_access_key | toString | b64enc }}
  {{- end }}
---
{{- end }}

  {{- if eq $global.storage_backend_type "nucleus" }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $global.nucleus.service_account_secret }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  username: {{ required "Please input Omniverse Nucleus server service account name: --set global.nucleus.username=<Service account username>" $global.nucleus.username | toString | b64enc }}
  password: {{ required "Please input Omniverse Nucleus server service account password: --set global.nucleus.password=<Service account password>" $global.nucleus.password | toString | b64enc }}
---
  {{- end }}

  {{- if eq $global.storage_backend_type "storage_api" }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $global.storage_api.authentication.secret_name }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  {{- if eq $global.storage_api.authentication.type "token" }}
  {{ $global.storage_api.authentication.secret_key }}: {{ required "Please input Storage API token: --set global.storage_api.authentication.token=<Storage API token>" $global.storage_api.authentication.token | toString | b64enc }}
  {{- else if eq $global.storage_api.authentication.type "openid" }}
  {{ $global.storage_api.authentication.openid.client_id_secret_key }}: {{ required "Please input Storage API OpenID client ID: --set global.storage_api.authentication.openid.client_id=<Storage API OpenID client ID>" $global.storage_api.authentication.openid.client_id | toString | b64enc }}
  {{ $global.storage_api.authentication.openid.client_secret_secret_key }}: {{ required "Please input Storage API OpenID client secret: --set global.storage_api.authentication.openid.client_secret=<Storage API OpenID client secret>" $global.storage_api.authentication.openid.client_secret | toString | b64enc }}
  {{ $global.storage_api.authentication.openid.scope_secret_key }}: {{ required "Please input Storage API OpenID client scope: --set global.storage_api.authentication.openid.scope=<Storage API OpenID client scope>" $global.storage_api.authentication.openid.scope | toString | b64enc }}
  {{- end }}
---
  {{- end }}

{{- end }}

{{- if $global.secrets.create.registry }}

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ $global.ngcImagePullSecretName }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "deepsearch-global.generatedImagePullSecret" . }}

---

{{- end }}

{{- if $global.secrets.create.ngc_api }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $global.ngcAPIKeySecretName }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  NGC_API_KEY: {{ required "Please input NGC API KEY: --set global.ngcAPIKey=<NGC API KEY>" $global.ngcAPIKey | toString | b64enc }}

---

{{- end }}


{{- if $global.secrets.create.embedding }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $global.embedding_deployment.authentication.secret_name }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  {{ $global.embedding_deployment.authentication.secret_key }}: {{ required "Please input Embedding Service API token: --set global.embedding_deployment.authentication.token=<Embedding Service API token>" $global.embedding_deployment.authentication.token | toString | b64enc }}
---
  {{- end }}

{{- if $global.secrets.create.rendering_service }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $values.deepsearch.microservices.rendering_service.authentication.api_key_secret_name }}
  annotations:
    {{- toYaml $global.secrets.annotations | nindent 4}}
  labels:
    {{- include "deepsearch-global.selectorLabels" . | nindent 4 }}
data:
  {{ $values.deepsearch.microservices.rendering_service.authentication.api_key_secret_field }}: {{ required "Please input Rendering Service API token: --set deepsearch.microservices.rendering_service.authentication.api_key=<Rendering Service API token>" $values.deepsearch.microservices.rendering_service.authentication.api_key | toString | b64enc }}
---
  {{- end }}
